- name: debug test for rhel hosts
  hosts: all
  #hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true

  tasks:
    - name: debug
      debug:
        msg: "debugging host - {{ inventory_hostname }}"

    - name: debug ansible facts 
      debug:
        msg: "debugging ansible facts - {{ ansible_facts }}"    
        

    
